project:
  type: website
  output-dir: docs

website:
  title: "Data Scientist"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - cert.qmd

format:
  html:
    theme:
      dark: slate
    css: styles.css
    toc: true



