project:
  type: website
  output-dir: docs

website:
  title: ""
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - cert.qmd

format:
  html:
    theme:
      light: spacelab
      dark: spacelab
    css: styles.css
    toc: true



