project:
  type: website
  output-dir: docs

website:
  title: "Jacques Booysen"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - demo.qmd
      - cert.qmd
      - data.qmd
      - modeling.qmd
      - papers.qmd
format:
  html:
    theme:
      light: spacelab
      dark: spacelab
    css: styles.css
    toc: true



