project:
  type: website
  output-dir: docs

website:
  title: "Data Scientist / Cloud Software Engineer"
  navbar:
    background: primary
    left:
      - href: index.qmd
        text: Home
      - cert.qmd

format:
  html:
    theme:
      light: darkly
      dark: darkly
    css: styles.css
    toc: true



